version: '3.8'

services: 
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes: 
      - ./volumes/mysql-data:/var/lib/mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: nest_api
